-- MySQL Script generated by MySQL Workbench
-- 10/29/16 17:39:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CloudiskDB
-- -----------------------------------------------------
-- 云盘系统数据库

-- -----------------------------------------------------
-- Schema CloudiskDB
--
-- 云盘系统数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CloudiskDB` DEFAULT CHARACTER SET utf8 ;
USE `CloudiskDB` ;

-- -----------------------------------------------------
-- Table `CloudiskDB`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CloudiskDB`.`file` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `md5` VARCHAR(45) NOT NULL COMMENT '库文件MD5，同时也是库文件名称',
  `path` VARCHAR(45) NOT NULL COMMENT '路径',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CloudiskDB`.`folder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CloudiskDB`.`folder` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `folder_name` VARCHAR(45) NOT NULL COMMENT '文件夹名称',
  `fa_id` INT NULL COMMENT '父文件夹',
  `user_id` INT NULL COMMENT '关联的用户ID',
  `creatime` DATE NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `fk_folder_folder1_idx` (`fa_id` ASC),
  CONSTRAINT `fk_folder_folder1`
    FOREIGN KEY (`fa_id`)
    REFERENCES `CloudiskDB`.`folder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CloudiskDB`.`user_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CloudiskDB`.`user_file` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `user_id` INT NULL COMMENT '关联用户ID',
  `file_name` VARCHAR(45) NOT NULL COMMENT '用户上传的文件名',
  `file_type` VARCHAR(20) NOT NULL COMMENT '文件类型',
  `file_size` VARCHAR(45) NOT NULL COMMENT '文件大小',
  `upload_time` DATE NOT NULL COMMENT '上传日期',
  `share` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否共享',
  `folder_id` INT NOT NULL COMMENT '关联父文件夹ID',
  `file_id` INT NOT NULL COMMENT '关联库文件ID',
  PRIMARY KEY (`id`),
  INDEX `fk_user_file_folder1_idx` (`folder_id` ASC),
  INDEX `fk_user_file_file1_idx` (`file_id` ASC),
  CONSTRAINT `fk_user_file_folder1`
    FOREIGN KEY (`folder_id`)
    REFERENCES `CloudiskDB`.`folder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_file_file1`
    FOREIGN KEY (`file_id`)
    REFERENCES `CloudiskDB`.`file` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CloudiskDB`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CloudiskDB`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `role_name` VARCHAR(20) NOT NULL COMMENT '权限角色名',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CloudiskDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CloudiskDB`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `name` VARCHAR(45) NOT NULL COMMENT '用户名',
  `email` VARCHAR(45) NOT NULL COMMENT '邮箱',
  `psd` VARCHAR(45) NOT NULL COMMENT '密码',
  `creatime` DATE NOT NULL COMMENT '创建时间',
  `role_id` INT NOT NULL COMMENT 'RBAC角色ID',
  `root_id` INT NOT NULL COMMENT '用户根目录ID',
  PRIMARY KEY (`id`),
  INDEX `fk_user_folder1_idx` (`root_id` ASC),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_folder1`
    FOREIGN KEY (`root_id`)
    REFERENCES `CloudiskDB`.`folder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `CloudiskDB`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CloudiskDB`.`pmsn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CloudiskDB`.`pmsn` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `name` VARCHAR(20) NOT NULL COMMENT '权限名称',
  `desc` VARCHAR(30) NULL COMMENT '权限内容描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CloudiskDB`.`role_pmsns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CloudiskDB`.`role_pmsns` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `role_id` INT NOT NULL COMMENT '关联角色ID',
  `pmsn_id` INT NOT NULL COMMENT '关联权限ID',
  PRIMARY KEY (`id`),
  INDEX `fk_role_pmsns_role2_idx` (`role_id` ASC),
  INDEX `fk_role_pmsns_pmsns1_idx` (`pmsn_id` ASC),
  CONSTRAINT `fk_role_pmsns_role2`
    FOREIGN KEY (`role_id`)
    REFERENCES `CloudiskDB`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_pmsns_pmsns1`
    FOREIGN KEY (`pmsn_id`)
    REFERENCES `CloudiskDB`.`pmsn` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
